
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SaleServiceService", targetNamespace = "http://webservice/", wsdlLocation = "http://kevin:8080/a1_V2_WebServices/SaleServiceService?wsdl")
public class SaleServiceService
    extends Service
{

    private final static URL SALESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESERVICESERVICE_EXCEPTION;
    private final static QName SALESERVICESERVICE_QNAME = new QName("http://webservice/", "SaleServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://kevin:8080/a1_V2_WebServices/SaleServiceService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESERVICESERVICE_WSDL_LOCATION = url;
        SALESERVICESERVICE_EXCEPTION = e;
    }

    public SaleServiceService() {
        super(__getWsdlLocation(), SALESERVICESERVICE_QNAME);
    }

    public SaleServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESERVICESERVICE_QNAME, features);
    }

    public SaleServiceService(URL wsdlLocation) {
        super(wsdlLocation, SALESERVICESERVICE_QNAME);
    }

    public SaleServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESERVICESERVICE_QNAME, features);
    }

    public SaleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SaleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SaleService
     */
    @WebEndpoint(name = "SaleServicePort")
    public SaleService getSaleServicePort() {
        return super.getPort(new QName("http://webservice/", "SaleServicePort"), SaleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SaleService
     */
    @WebEndpoint(name = "SaleServicePort")
    public SaleService getSaleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "SaleServicePort"), SaleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESERVICESERVICE_EXCEPTION!= null) {
            throw SALESERVICESERVICE_EXCEPTION;
        }
        return SALESERVICESERVICE_WSDL_LOCATION;
    }

}
