
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SaleService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SaleService {


    /**
     * 
     * @param arg0
     * @return
     *     returns webservice.SalesOrderFact
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSalesFact", targetNamespace = "http://webservice/", className = "webservice.GetSalesFact")
    @ResponseWrapper(localName = "getSalesFactResponse", targetNamespace = "http://webservice/", className = "webservice.GetSalesFactResponse")
    @Action(input = "http://webservice/SaleService/getSalesFactRequest", output = "http://webservice/SaleService/getSalesFactResponse")
    public SalesOrderFact getSalesFact(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://webservice/", className = "webservice.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://webservice/", className = "webservice.CreateProductResponse")
    @Action(input = "http://webservice/SaleService/createProductRequest", output = "http://webservice/SaleService/createProductResponse")
    public void createProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createTime", targetNamespace = "http://webservice/", className = "webservice.CreateTime")
    @ResponseWrapper(localName = "createTimeResponse", targetNamespace = "http://webservice/", className = "webservice.CreateTimeResponse")
    @Action(input = "http://webservice/SaleService/createTimeRequest", output = "http://webservice/SaleService/createTimeResponse")
    public void createTime(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

    /**
     * 
     * @param arg5
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @param arg6
     * @param arg7
     */
    @WebMethod
    @RequestWrapper(localName = "createOrderFact", targetNamespace = "http://webservice/", className = "webservice.CreateOrderFact")
    @ResponseWrapper(localName = "createOrderFactResponse", targetNamespace = "http://webservice/", className = "webservice.CreateOrderFactResponse")
    @Action(input = "http://webservice/SaleService/createOrderFactRequest", output = "http://webservice/SaleService/createOrderFactResponse")
    public void createOrderFact(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        int arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        double arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        int arg7);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createSupplier", targetNamespace = "http://webservice/", className = "webservice.CreateSupplier")
    @ResponseWrapper(localName = "createSupplierResponse", targetNamespace = "http://webservice/", className = "webservice.CreateSupplierResponse")
    @Action(input = "http://webservice/SaleService/createSupplierRequest", output = "http://webservice/SaleService/createSupplierResponse")
    public void createSupplier(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://webservice/", className = "webservice.CreateEmployee")
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://webservice/", className = "webservice.CreateEmployeeResponse")
    @Action(input = "http://webservice/SaleService/createEmployeeRequest", output = "http://webservice/SaleService/createEmployeeResponse")
    public void createEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://webservice/", className = "webservice.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://webservice/", className = "webservice.CreateCustomerResponse")
    @Action(input = "http://webservice/SaleService/createCustomerRequest", output = "http://webservice/SaleService/createCustomerResponse")
    public void createCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "id_validiation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "id_validiation", targetNamespace = "http://webservice/", className = "webservice.IdValidiation")
    @ResponseWrapper(localName = "id_validiationResponse", targetNamespace = "http://webservice/", className = "webservice.IdValidiationResponse")
    @Action(input = "http://webservice/SaleService/id_validiationRequest", output = "http://webservice/SaleService/id_validiationResponse")
    public boolean idValidiation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
